#!usr/bin/env bash

echo "🚀Setting up WSL!🚀"
echo "Starting to install all the things..."
echo "===================================="

echo "\n🚀Setting up python..."
# python
curl -Ls https://raw.githubusercontent.com/NicDom/dev-setup/main/python-setup | bash

# install latest git
echo "✨Installing latest git..."
sudo add-apt-repository ppa:git-core/ppa
sudo apt update -y
sudo apt install -y git

# curl
# if you want to have the latest version run the command below
# sudo add-apt-repository ppa:savoury1/curl34 -y
# echo "✨Installing curl..."
# sudo apt install curl -y

# nvm
echo "✨Installing nvm..."
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
nvm install node

# brew
echo "✨Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# install neovim
echo "✨Installing neovim..."
brew install neovim
# echo "Downloading the Debian binary..."
# wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
# echo "Installing the Debian binary..."
# sudo apt install ./nvim-linux64.deb
# echo "Cleaning up..."
# rm nvim-linux64.deb

echo "✨Installing lazygit..."
brew install lazygit

# install zsh
echo "🚀Setting up zsh..."
curl -Ls https://raw.githubusercontent.com/NicDom/dev-setup/main/zsh-installer | bash

echo "🚀Finished installing all the things!"
echo "Following packages have been installed:"
echo "git, curl, zsh, ripgrep, fzf, bat, pyenv, poetry, pipx, nvm, brew, neovim, cookiecutter, nox, nox-poetry"

exec zsh

echo "\n===================================="
echo "If you want to use zsh as your default shell run the following command:"
echo "chsh -s $(which zsh)"

