#!usr/bin/env bash

echo "🚀Setting up WSL!🚀"
echo "Starting to install all the things..."
echo "===================================="
echo "🚀Setting up python..."
# python
curl -Ls https://raw.githubusercontent.com/NicDom/dev-setup/main/python-setup | bash

# install zsh
echo "🚀Setting up zsh..."
curl -Ls https://raw.githubusercontent.com/NicDom/dev-setup/main/zsh-installer | bash

# install latest git
# echo "✨Installing latest git..."
# sudo add-apt-repository ppa:git-core/ppa
# sudo apt update -y
# sudo apt install -y git

# curl
# if you want to have the latest version run the command below
# sudo add-apt-repository ppa:savoury1/curl34 -y
# echo "✨Installing curl..."
# sudo apt install curl -y




# nvm
echo "✨Installing nvm..."
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

# brew
echo "✨Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# node
# brew install node
# nvm install npm
# nvm install node
# nvm install --lts

# install neovim
echo "✨Installing neovim..."

# echo "Downloading the Debian binary..."
# wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
# echo "Installing the Debian binary..."
# sudo apt install ./nvim-linux64.deb
# echo "Cleaning up..."
# rm nvim-linux64.deb

brew install neovim
# sudo apt-get install -y software-properties-common
# sudo add-apt-repository ppa:neovim-ppa/stable
# sudo apt-get update -y
# sudo apt-get install -y neovim

echo "🚀Finished installing all the things!"
echo "Following packages have been installed:"
echo "git, curl, zsh, ripgrep, fzf, bat, pyenv, poetry, pipx, nvm, brew, neovim, cookiecutter, nox, nox-poetry"
